# Generated by Django 3.1.2 on 2020-11-28 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_order_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listitem',
            name='shoppingcart',
        ),
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
    ]
