# Generated by Django 3.1.2 on 2020-11-07 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_listitem_product_shoppingcart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.product'),
        ),
    ]
