# Generated by Django 3.1.2 on 2020-11-28 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201128_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
