# Generated by Django 3.1.2 on 2020-11-28 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_listitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.order'),
        ),
    ]
