# Generated by Django 3.1.2 on 2020-11-07 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201107_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listitem',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='listitem',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='listitem',
            name='product_price',
        ),
        migrations.AddField(
            model_name='listitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.product'),
        ),
    ]
