# Generated by Django 3.1.2 on 2020-11-28 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listitem',
            name='user',
        ),
    ]
