# Generated by Django 3.1.2 on 2020-11-09 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20201108_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.IntegerField(max_length=1, null=True),
        ),
    ]
